### ISSUE TITLE
1秒以内に生成された複数のファイルが別れていない

### ISSUE THREAD

**Issue by kobi32768** [anatawa12/vrc-log-renamer#4]
#1 の実装が不完全だと思われます
![image](https://user-images.githubusercontent.com/40712426/201501573-a9e38083-083e-463c-98ab-5cb682975403.png)
![image](https://user-images.githubusercontent.com/40712426/201501554-e05dd675-cba0-4bc3-b124-6b57bc174579.png)

**Comment by anatawa12** [comment]
コンフィグを見せていただきたいです。

**Comment by kobi32768** [comment]
```toml
[source]
pattern = "^output_log_\\d{2}-\\d{2}-\\d{2,}\\.txt$"

[output]
folder = "C:\\Users\\kobi32768\\AppData\\LocalLow\\VRChat\\VRChat\\Logs"
pattern = "output_log_%0Y-%0m-%0d_%0H-%0M-%0S{regex:in_sec_num}.txt"
file_ctime = true
```
でした
コンフィグのリセットがかかったら条件が変わってたのでそれが原因っぽいです (おそらく条件で n 番目の値を保持するようにしていた？)
