### ISSUE TITLE
設定ファイルの出力形式が保存時にGUI内と異なりロードでエラーが出る

### ISSUE THREAD

**Issue by kobi32768** [anatawa12/vrc-log-renamer#7]
出力形式に `%.3f` を入れると保存された設定ファイルに `.` の位置がずれて `%3.f` と書き込まれるため次回起動時に出力形式が不正とエラーが出る
![image](https://user-images.githubusercontent.com/40712426/201507335-e48986a9-fe70-40b1-9927-f3f228d70d65.png)
![image](https://user-images.githubusercontent.com/40712426/201507379-ba1d0d02-6c2f-4097-a82f-ddbb8f3184ea.png)

```toml
[source]

[output]
folder = "C:\\Users\\kobi32768\\AppData\\LocalLow\\VRChat\\VRChat\\Logs"
pattern = "output_log_%0Y-%0m-%0d_%0H-%0M-%0S%3.f.txt"
file_ctime = true
```
